#ifndef __CONFIG_H

#define __CONFIG_H
/** PRODUCT INFORMATION **/
#cmakedefine PRODUCT_NAME @PRODUCT_NAME@
#cmakedefine PRODUCT_VERSION_MAJOR @PRODUCT_VERSION_MAJOR@
#cmakedefine PRODUCT_VERSION_MINOR @PRODUCT_VERSION_MINOR@
#cmakedefine PRODUCT_VERSION_TYPE @PRODUCT_VERSION_TYPE@
#cmakedefine PRODUCT_STRING @PRODUCT_STRING@

#endif // __CONFIG_H
